### ISSUE TITLE
image channel

### ISSUE THREAD

**Issue by charming2992** [TannerGilbert/Computer-Vision-Synthetic-Data-Generation#3]
![image](https://user-images.githubusercontent.com/106571854/188851479-4c1abef9-ec8b-4b29-a017-572ec68c5aae.png)
alpha_mask = fg_image.getchannel(3): band index out of range
I change it to 0/1/2 worked, but the generated pic distortion.
How can I solve it

**Comment by TannerGilbert** [comment]
Your foreground images need to have four channels ([RGBA](https://www.w3schools.com/cssref/func_rgba.asp)). The fourth channel is alpha. This channel is automatically added if you use the [create_input_images_from_labelme.py](https://github.com/TannerGilbert/Computer-Vision-Synthetic-Data-Generation/blob/master/create_input_images_from_labelme.py) script as described in the README. If you don't want to use the script, you can add the alpha channel yourself either with some kind of graphics editor like Photoshop or with code like [create_input_images_from_labelme.py#L50](https://github.com/TannerGilbert/Computer-Vision-Synthetic-Data-Generation/blob/master/create_input_images_from_labelme.py#L50).

Also, please give your issues a descriptive name, and if you solve a problem you describe in an issue, please leave a comment with the resolution to help others that might face the same problem in the future.

**Comment by charming2992** [comment]
Thanks a lot
